
import dash
from dash.dependencies import Input, Output
import dash_bootstrap_components as dbc
from dash import html
import numpy as np
import warnings
from dash import dcc
import plotly.graph_objs as go
import plotly.express as px
from dash import dash_table
import pandas as pd
from collections import OrderedDict
warnings.filterwarnings("ignore")


data_election = OrderedDict(
    [
        (
            "Desc",
            [
                'Body suits',
                 'Square Neck Bodysuit',
                 'Jumpsuit',
                 'Dress',
                 'Dress',
                 'Sweater',
                 'Shoes',
                 'Rings',
                 'Rings',
                 'Earrings',
                 'Earrings',
                 'Bracelet',
                 'Jewelry',
                 'Serums',
                 'Sunscreen',
                 'Pimple Patches',
                 'Lip gloss',
                 'Lash serum',
                 'Ulta/sephora gift cards',
                 'Money,Giftcards,Tattoo,Nails',
                 'Bonnets',
                 'Shea moisture hair products',
                 'PJ set',
                 'Lounge set',
                 'Sweats',
                 'Long sleeves',
                 'Short sleeve',
                 'One piece',
                 'Soundbar',
                 'Tv stand',
                 'Comforter set(full)',
                 'New Balance 550',
                 'Face serums',
                 'Tinted moisturizer',
                 'Leggings',
                 'Top',
                 'Shoes',
                 'Gym bag',
                 'Creatine',
                 'Laptop case',
                 'Airpod pro',
                 'Lemberi chair',
                 'Elta MD Sunscreen',
                 'Miss Dior perfume',
                 'Eye masks',
                 'Sculptural rings/earrings',
                 'Gucci/Dior Saddle',
                 'Lululemon free to be bra-wildlight support a/b cup',
                 'Lululemon swiftly tech long sleeve shirt 2.0 race length',
                 'Skims essential crew neck long sleeve bodysuit',
                 'Skims essential mock neck long sleeve bodysuit',
                 'Nike sportswear club fleece mid size rise joggers',
                 'Nike sportswear phoenix fleece',
                 'Section sofa',
                 'Floors',
                 'Laneige lip masks',
                 'Glow recipe set',
                 'Drunk elephant skincare',
                 'ILIA mascara',
                 'Ordinary lash serum',
                 'Patrick star one size setting spray',
                 'Charlotte Tilbury pillow talk lip kit',
                 'Dossier perfume',
                 'Bum bum mini set',
                 'Vanilla perfume discovery set',
                 'Cheirosa travel set',
                 'Lip gloss',
                 'Ordinary serum',
                 'Elta MD sunscreen',
                 'Drunk elephant',
                 'Beachwaver curling iron',
                 'Skincare headband',
                 'Rare beauty highlighter',
                 'Rare beauty bronzing stick',
                 'Rare beauty lip oil',
                 'Squishmallow',
                 'Squishmallow',
                 'Keychain wallet',
                 'Keychain',
                 'Money/Gift cards(aerie, target, amazon,etc)',
                 'Tasman slippers',
                 'Leggins',
                 'Two piece long sleeve set',
                 'Sleeveless bodysuit',
                 'Square neck bodysuit',
                 'Wide leg pants',
                 'Dandy hoodie',
                 'Skylar lace tank',
                 'White fox taking off top',
                 'For the culture hoodie',
                 'Aerie leggings',
                 'Nike pants',
                 'Sza hoodies',
                 'Sza shirt',
                 'Evry jewls necklace',
                 'Evry jewls earrings',
                 'Evry jewls hoops',
                 'Car',
                    'Jordan 4 retro',
                    'Samba classic',
                    'Tasman Slipper',
                    'Gap sweatshirts/sweatpants',
                    'Pura vida bracelets',
                    'Get back necklaces',
                    'Ransom clothing',
                    'Swiftly Tech long sleeve shirt',
                    'Portals Moth t-shirt',
                    'Beetles gel nail polish',
                    'License plate frame',
                    'Airbrush Kit',
                    'Fike hoodie',
                    'Nail charms',
                    'Nail charms',
                    'Glass Crystals',
                    'Pearls kits',
                    'Nail gel'
            ],
        ),
        (
            "Link",
            ['<a href= "https://www.amazon.com/OQQ-Womens-Bodysuits-Ribbed-Square/dp/B0BHNKSHWS/ref=sr_1_5?crid=1NKC0JFRKXJ1V&keywords=oqq%2Bbodysuit&qid=1700760825&sprefix=OQQ%2Caps%2C107&sr=8-5&th=1&psc=1">Link</a>',
                 '<a href= "https://www.amazon.com/QINSEN-Bodysuit-Sleeve-Square-Double/dp/B0CCDJVWQW/ref=sr_1_3_sspa?crid=1NKC0JFRKXJ1V&keywords=oqq%2Bbodysuit&qid=1700760825&sprefix=OQQ%2Caps%2C107&sr=8-3-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1&psc=1">Link</a>',
                 '<a href= "https://www.amazon.com/dp/B0CBB8GQHX/ref=sspa_dk_detail_5?pd_rd_i=B0CBB8W3P5&pd_rd_w=mvFgo&content-id=amzn1.sym.f734d1a2-0bf9-4a26-ad34-2e1b969a5a75&pf_rd_p=f734d1a2-0bf9-4a26-ad34-2e1b969a5a75&pf_rd_r=33TP4QTKRA2XJY381XQ0&pd_rd_wg=c1gTB&pd_rd_r=8d1af117-86fe-4392-9556-be60dd601967&s=apparel&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw&th=1&psc=1">Link</a>',
                 '<a href= "https://www.amazon.com/dp/B0CJDTHHJJ/ref=sspa_dk_detail_1?pd_rd_i=B0CJDTHHJJ&pd_rd_w=jM8zh&content-id=amzn1.sym.f734d1a2-0bf9-4a26-ad34-2e1b969a5a75&pf_rd_p=f734d1a2-0bf9-4a26-ad34-2e1b969a5a75&pf_rd_r=8NHYB5ZZYRSNFGYNDPVA&pd_rd_wg=crCEZ&pd_rd_r=5faf8b10-345b-41cf-9e24-438cbb250e7f&s=apparel&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw&th=1&psc=1">Link</a>',
                 '<a href= "https://www.amazon.com/dp/B0B5WTSSQ9/ref=sspa_dk_detail_2?pd_rd_i=B0B5WTSSQ9&pd_rd_w=SzzSM&content-id=amzn1.sym.f734d1a2-0bf9-4a26-ad34-2e1b969a5a75&pf_rd_p=f734d1a2-0bf9-4a26-ad34-2e1b969a5a75&pf_rd_r=GV3RV2JZ7TG2VSVXV9JF&pd_rd_wg=lx416&pd_rd_r=0a7263b6-66b4-4e68-a04b-0dc0ae51dcf7&s=apparel&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw&th=1&psc=1">Link</a>',
                 '<a href= "https://www.amazon.com/Verdusa-Womens-Knitted-Cardigan-Sweater/dp/B0BTSFXHPQ/ref=sxin_38_pa_sp_search_thematic_sspa?content-id=amzn1.sym.e0f7d8e5-6c81-4b07-b83b-2ec00eebe75e%3Aamzn1.sym.e0f7d8e5-6c81-4b07-b83b-2ec00eebe75e&crid=3ELFH8QBI7CF&cv_ct_cx=cardigan%2Bsweaters%2Bfor%2Bwomen&keywords=cardigan%2Bsweaters%2Bfor%2Bwomen&pd_rd_i=B0BTSFXHPQ&pd_rd_r=9898d2cf-74e8-4896-852c-450372d18236&pd_rd_w=RE9yx&pd_rd_wg=3hbS3&pf_rd_p=e0f7d8e5-6c81-4b07-b83b-2ec00eebe75e&pf_rd_r=N2CCCF7QDNSP6PKEAMNV&qid=1700770625&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&sprefix=cardigan%2Caps%2C98&sr=1-1-2c727eeb-987f-452f-86bd-c2978cc9d8b9-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9zZWFyY2hfdGhlbWF0aWM&th=1&psc=1">Link</a>',
                 '<a href= "https://stockx.com/new-balance-9060-mushroom">Link</a>',
                 '<a href= "https://www.amazon.com/Celestial-Sparkling-Plating-Friendship-Stackable/dp/B0C8FQQ92R/ref=sr_1_27?crid=1PUIIQLSP1594&keywords=rings&qid=1700762966&sprefix=rings%2Caps%2C109&sr=8-27&th=1">Link</a>',
                 '<a href= "https://www.amazon.com/Simulated-Diamond-Designs-Stacking-Layering/dp/B0C58298F8/ref=sxbs_pa_sp_search_thematic_btf_sspa?content-id=amzn1.sym.b1377db7-0b82-41e8-a17f-9af4adf1b530%3Aamzn1.sym.b1377db7-0b82-41e8-a17f-9af4adf1b530&crid=1PUIIQLSP1594&cv_ct_cx=rings&keywords=rings&pd_rd_i=B0C58298F8&pd_rd_r=7a59b3bf-8e31-419c-b35b-8c7e419f5c59&pd_rd_w=pZt5W&pd_rd_wg=BELvz&pf_rd_p=b1377db7-0b82-41e8-a17f-9af4adf1b530&pf_rd_r=ZSG6SZCJP71J92F0C8EM&qid=1700763628&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&sprefix=rings%2Caps%2C109&sr=1-1-0593f4a3-2672-42a2-bca6-c8b865efb498-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9zZWFyY2hfdGhlbWF0aWNfYnRm&th=1&psc=1">Link</a>',
                 '<a href= "https://evryjewels.com/collections/best-sellers/products/brandy-earrings">Link</a>',
                 '<a href= "https://www.amazon.com/dp/B0CH4HWPM9/ref=sspa_dk_detail_0?pd_rd_i=B0CH4HWPM9&pd_rd_w=VX293&content-id=amzn1.sym.f734d1a2-0bf9-4a26-ad34-2e1b969a5a75&pf_rd_p=f734d1a2-0bf9-4a26-ad34-2e1b969a5a75&pf_rd_r=V0EJHS70FJX7JDBM7GJR&pd_rd_wg=J7aCQ&pd_rd_r=1ad6a6cf-b966-463e-900e-96b867fb96fb&s=jewelry&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw&th=1">Link</a>',
                 '<a href= "https://evryjewels.com/collections/bracelets/products/dont-cross-me-bracelet">Link</a>',
                 'N/A',
                 '<a href= "https://theordinary.com/en-us/the-most-loved-gift-set-100633.html?dwvar_100633_size=1%20set&quantity=1&gad_source=1&gclid=CjwKCAiAjfyqBhAsEiwA-UdzJAjZIUiHRZm3FFF2Mc0S9gaqDrhAo990WezYZ-R2sHq8dKaZLpqmERoCQt0QAvD_BwE&gclsrc=aw.ds">Link</a>',
                 '<a href= "https://www.amazon.com/EltaMD-Moisturizer-Hyaluronic-Mineral-Based-Protection/dp/B00J5KDCO2/ref=asc_df_B00J5KDCO2/?tag=hyprod-20&linkCode=df0&hvadid=312153186848&hvpos=&hvnetw=g&hvrand=8453952482864002813&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9011767&hvtargid=pla-435694681088&psc=1&mcid=c4873a6c4ec239a6bc003961e0692c4b&gclid=CjwKCAiAjfyqBhAsEiwA-UdzJCXcs3JIbeAKdLW4aQpZbYpI1gixicrfjPJXt8bef563xjKscXy3qhoCQJ0QAvD_BwE">Link</a>',
                 'N/A',
                 '<a href= "https://www.amazon.com/Hydrating-Plumping-Transparent-Moisturizing-Non-Sticky/dp/B0C9C4RVBL/ref=sr_1_7?crid=1QHMFD8OBAXEW&keywords=lip%2Bgloss&qid=1700770144&sprefix=lip%2Caps%2C125&sr=8-7&th=1">Link</a>',
                 '<a href= "https://theordinary.com/en-us/multi-peptide-lash-brow-serum-100111.html?dwvar_100111_size=eu5ml&quantity=1&gad_source=1&gclid=CjwKCAiAjfyqBhAsEiwA-UdzJOmyp8tLvW4FWJpDqTHHQV9umj4szRV02rAVmOXDk16H8htPxr7OYhoC_lAQAvD_BwE&gclsrc=aw.ds">Link</a>',
                 'N/A',
                 'N/A',
                 '<a href= "https://www.amazon.com/Bonnet-Sleeping-Bonnets-Braids-shower/dp/B0C1B8RMJ9/ref=sr_1_7?crid=2LH1LNQ7U5KUY&keywords=bonnets&qid=1700771167&sprefix=bonnets%2Caps%2C126&sr=8-7&th=1">Link</a>',
                 '<a href= "https://www.ulta.com/search?search=SheaMoisture+Coconut+%26+Hibiscus">Link</a>',
                 '<a href= "https://www.amazon.com/WZTYYDS-Knitted-Sleeveless-Outfits-Streetwear/dp/B0BVFCZ7MN/ref=sr_1_13_sspa?crid=2SI1JN6B8OE0O&keywords=pj%2Bsets&qid=1701112077&sprefix=pj%2Bsets%2Caps%2C107&sr=8-13-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&th=1&psc=1">Link</a>',
                 '<a href= "https://us.boohoo.com/petite-acid-wash-hoody-and-jogger-tracksuit/GZZ52716.html?color=115">Link</a>',
                 '<a href= "https://us.boohoo.com/dsgn-studio-woven-label-straight-leg-jogger/GZZ61325.html?color=115">Link</a>',
                 '<a href= "https://www.amazon.com/HYZ-Womens-Casual-Seamless-Darkgrey/dp/B0CBJT6XB5/ref=sr_1_2_sspa?crid=U0JEKZ9NXH46&keywords=skims%2Bdupe&qid=1701393725&sprefix=skim%2Bdupe%2Caps%2C115&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1&psc=1">Link</a>',
                 '<a href= "https://www.amazon.com/Womens-Casual-Basic-Sleeve-Shirts/dp/B0BW2XQCQQ/ref=sr_1_1_sspa?crid=U0JEKZ9NXH46&keywords=skims%2Bdupe&qid=1701393725&sprefix=skim%2Bdupe%2Caps%2C115&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1&psc=1">Link</a>',
                 '<a href= "https://www.amazon.com/SUUKSESS-Ribbed-Stretchy-Jumpsuits-Workout/dp/B0BQ2FKM1C/ref=sr_1_13?crid=1AEH3QZUKD865&keywords=suuksess%2Blong%2Bsleeve&qid=1701399627&sprefix=suu%2Caps%2C102&sr=8-13&th=1">Link</a>',
                 '<a href= "https://www.bestbuy.com/site/vizio-2-1-channel-v-series-home-theater-sound-bar-with-dts-virtualx-and-wireless-subwoofer-black/6471428.p?skuId=6471428&extStoreId=571&utm_source=feed&ref=212&loc=1&gad_source=1&gclid=Cj0KCQiAgqGrBhDtARIsAM5s0_m-211ZQdn3Wxe-BhTc_2JoXTb0KosrRArQj6k9Zd1_jRM6gkbY4JQaAkwoEALw_wcB&gclsrc=aw.ds">Link</a>',
                 '<a href= "https://www.homedepot.com/pep/HOMCOM-63-in-Black-TV-Stand-with-Storage-Fits-TV-s-up-to-65-in-839-123V80BK/319830349?source=shoppingads&locale=en-US&pla&mtc=SHOPPING-BF-HDH-GGL-D59H-059_034_INT_FURN-NA-NA-NA-PMAX-NA-HDH-NA-NA-NBR-NA-NA-NA-%7C059_034_006_HOME_ENTERTAINMENT_FURN%7C_PMAX_phase_5&cm_mmc=SHOPPING-BF-HDH-GGL-D59H-059_034_INT_FURN-NA-NA-NA-PMAX-NA-HDH-NA-NA-NBR-NA-NA-NA-%7C059_034_006_HOME_ENTERTAINMENT_FURN%7C_PMAX_phase_5-71700000113210468--&gad_source=1&gclid=Cj0KCQiAgqGrBhDtARIsAM5s0_kM04trF_bJark5_sCfHx-bDNPy4ayJBZc9SZDQSCh4dFWeDuBNA94aAsr8EALw_wcB&gclsrc=aw.ds">Link</a>',
                 '<a href= "https://www.wayfair.com/East-Urban-Home--Amsterdam-Black-100%25-Cotton-4-Piece-Duvet-Cover-Set-V114478466-L1221-K~W007474503.html?refid=GX603876547115-W007474503&device=c&ptid=1676086665785&network=g&targetid=pla-1676086665785&channel=GooglePLA&ireid=156291510&fdid=1817&gad_source=1&gclid=Cj0KCQiAgqGrBhDtARIsAM5s0_nemQYkWMuSlpeR9aBLb5ytQuum8gvXppUp-EXF9w6pzAvST6o2ZHkaAhQ8EALw_wcB">Link</a>',
                 '<a href= "https://www.newbalance.com/pd/550/BBW550V1-43973.html?dwvar_BBW550V1-43973_style=BBW550BG">Link</a>',
                 '<a href= "https://www.amazon.com/Ordinary-Caffeine-Hyaluronic-Niacinamide-Blemishes/dp/B07QFHZZZL/ref=sr_1_9?crid=2EF8LWNOC436U&keywords=skincare&qid=1701399840&sprefix=skincare%2Caps%2C130&sr=8-9">Link</a>',
                 '<a href= "https://www.amazon.com/EltaMD-Moisturizer-Hyaluronic-Mineral-Based-Protection/dp/B00J5KDCO2/ref=sr_1_2_sspa?crid=30LTQL2FLAERL&keywords=tinted+spf+moisturizer+for+face&qid=1701399970&sprefix=tinted+spf+%2Caps%2C107&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1">Link</a>',
                 '<a href= "https://www.amazon.com/OVESPORT-Seamless-Waisted-Leggings-Athletic/dp/B0BHSM8RQH/ref=sr_1_8?crid=3TQ9KTGS6E5WK&keywords=gym&qid=1701626200&sprefix=gym%2B%2Caps%2C182&sr=8-8&th=1&psc=1">Link</a>',
                 '<a href= "https://www.amazon.com/Womens-Compression-Workout-Athletic-Sleeve/dp/B07XCJCSDW/ref=sr_1_1_sspa?crid=1DFFF2AEGRM9Z&keywords=gym%2Blong%2Bsleeve&qid=1701626246&sprefix=gym%2Blongsleeve%2Caps%2C122&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1&psc=1">Link</a>',
                 '<a href= "https://www.adidas.com/us/ozweego-shoes-kids/IG7419.html">Link</a>',
                 '<a href= "https://www.gymshark.com/products/gymshark-sharkhead-backpack-black-aw23">Link</a>',
                 '<a href= "https://www.amazon.com/Creatine-Lemonade-Cognition-Monohydrate-Micronized/dp/B0BQ5S3P3P/ref=sr_1_3_sspa?crid=2A6VQ08Q4WN70&keywords=creatine&qid=1701628795&rdc=1&sprefix=creatine%2Caps%2C288&sr=8-3-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1">Link</a>',
                 '<a href= "https://www.amazon.com/Teryeefi-A2338-A2289-A2251-Rubberized/dp/B09WN3P2FR/ref=sr_1_24?crid=2SAZVGW336VBU&keywords=macbook%2Bcover&qid=1701402034&sprefix=macbook%2Bcover%2Caps%2C102&sr=8-24&th=1">Link</a>',
                 '<a href= "https://www.bestbuy.com/site/apple-airpods-pro-2nd-generation-with-magsafe-case-usbc-white/6447382.p?skuId=6447382">Link</a>',
                 '<a href= "https://www.amazon.com/LEMBERI-Armless-Rocking-Ergonomic-Computer/dp/B0B8MRJCLS/ref=sr_1_4?crid=1MVNLQ8HC0XLU&keywords=lemberi%2Bchair&qid=1701991661&rnid=2941120011&s=furniture&sprefix=lemberi%2Bchair%2Caps%2C204&sr=1-4&ufe=app_do%3Aamzn1.fos.17d9e15d-4e43-4581-b373-0e5c1a776d5d&th=1">Link</a>',
                 '<a href= "https://www.amazon.com/Sunscreen-Broad-Spectrum-Acne-Prone-Dermatologist-Recommended-Mineral-Based/dp/B00ZPWR0N8/ref=sr_1_2_sspa?crid=1HNYZOA716YWG&keywords=elta+md&qid=1700849798&sprefix=elta+md%2Caps%2C111&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1">Link</a>',
                 '<a href= "https://www.sephora.com/product/dior-miss-dior-eau-de-parfum-P474316?skuId=2467371">Link</a>',
                 '<a href= "https://www.amazon.com/Hyaluronic-Treatment-Wrinkles-Puffiness-Lightens/dp/B07Y2VBJM3/ref=sr_1_18?crid=28YOPQZX75RQ5&keywords=eye+mask+skincare+with+collagen&qid=1700849989&s=beauty&sprefix=eye+mask+skincare+with+collagen%2Cbeauty%2C89&sr=1-18#customerReviews">Link</a>',
                 'N/A',
                 'N/A',
                 '<a href= "https://shop.lululemon.com/p/women-sports-bras/Free-To-Be-Bra-Wild/_/prod2810229?color=60310&sz=4">Link</a>',
                 '<a href= "https://shop.lululemon.com/p/tops-long-sleeve/Swiftly-Tech-LS-2-Race/_/prod9750541?color=65188">Link</a>',
                 '<a href= "https://skims.com/products/essential-crew-neck-long-sleeve-bodysuit-sienna">Link</a>',
                 '<a href= "https://skims.com/products/essential-mock-neck-long-sleeve-bodysuit-light-grey">Link</a>',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 '<a href= "https://www.sephora.com/product/midnight-minis-set-P507085?country_switch=us&lang=en&skuId=2698397&om_mmc=ppc-GG_17791296883___2698397__9011767_c&country_switch=us&lang=en&gad_source=4&gclid=Cj0KCQiAr8eqBhD3ARIsAIe-buMRBkuVnQwKbif-iv9oE-1WxT3FqO_ZzDnQKr2NGzjhgTd872JPj5UaAh4hEALw_wcB&gclsrc=aw.ds">Link</a>',
                 '<a href= "https://www.sephora.com/product/glow-recipe-fruit-babies-bestsellers-kit-P504171?country_switch=us&lang=en&skuId=2640332&om_mmc=ppc-GG_17791296883___2640332__9011767_c&country_switch=us&lang=en&gad_source=4&gclid=Cj0KCQiAr8eqBhD3ARIsAIe-buOHdeyU1RIoZynmrkJBflC-NKSSH9TM1GQCV5cJSZxHNaM4nogLvD0aAnrxEALw_wcB&gclsrc=aw.ds">Link</a>',
                 '<a href= "https://www.sephora.com/product/b-hydra-intensive-hydration-gel-P406712?skuId=1785856&icid2=products%20grid:p406712:product">Link</a>',
                 '<a href= "https://www.kohls.com/product/prd-5017849/ilia-limitless-lash-lengthening-clean-mascara.jsp?skuid=71463747&CID=shopping15&utm_campaign=MAKEUP%20-%20EYE%20%26%20LIP&utm_medium=CSE&utm_source=google&utm_product=71463747&utm_campaignid=20485366750&CID=shopping30&utm_campaign=MediumSSCSephora&utm_medium=CSE&utm_source=google&utm_campaignid=20485366750&gad_source=4&gclid=Cj0KCQiApOyqBhDlARIsAGfnyMqne8mNwS07cau7bHnp62Z5EuFKnGp-WWL-bUzctk-zdoEAakSNOxcaAt5WEALw_wcB&gclsrc=aw.ds">Link</a>',
                 '<a href= "https://www.ulta.com/p/multi-peptide-lash-brow-serum-pimprod2033455?sku=2592847&cmpid=PS_Non!google!Product_Listing_Ads&utm_source=google&utm_medium=paidsearch&cagpspn=pla&CATCI=&CAAGID=&CAWELAID=330000200002891410&gad_source=1&gclid=Cj0KCQiApOyqBhDlARIsAGfnyMrY8XGZ9jZjMOT_EWeL0SVZBwRJQ34pRCx92Qtj68ZXHA5N4mkkZ5YaAl3zEALw_wcB">Link</a>',
                 '<a href= "https://www.kohls.com/product/prd-5161311/onesize-by-patrick-starrr-on-til-dawn-mattifying-waterproof-setting-spray.jsp?skuid=83060094&CID=shopping30&utm_campaign=MAKEUP%20-%20COMPLEXION&utm_medium=CSE&utm_source=google&utm_product=83060094&utm_campaignid=20502755756&CID=shopping30&utm_campaign=SSCSephora&utm_medium=CSE&utm_source=google&utm_campaignid=20502755756&gad_source=1&gclid=Cj0KCQiApOyqBhDlARIsAGfnyMoLlYlUQRucuCG65zEKb48m4VFtMYQYfv22BCFh1vPhSOJHsTPNHkkaAsQ0EALw_wcB&gclsrc=aw.ds">Link</a>',
                 '<a href= "https://www.sephora.com/product/charlotte-tilbury-mini-pillow-talk-lip-duo-P458268?country_switch=us&lang=en&skuId=2339620&om_mmc=ppc-GG_17791296877___2339620__9011767_c&country_switch=us&lang=en&gad_source=1&gclid=Cj0KCQiApOyqBhDlARIsAGfnyMpTmPctSxt5W9-MNWV8X8uWvftVfS8U6AXDlut7_8P6DJUJ9aI1hS0aApk1EALw_wcB&gclsrc=aw.ds">Link</a>',
                 '<a href= "https://dossier.co/products/ambery-vanilla?_pos=1&_psq=amberry&_ss=e&_v=1.0&utm_source=google&utm_medium=cpc&utm_campaign=US_Search_M_Brand+DossierProductsName&gad_source=1&gclid=Cj0KCQiApOyqBhDlARIsAGfnyMpWr7kiGrXzHyt5yrVCr8A4qW6uuJxUr1WqOlNlHfKc0tQJrjInrrYaAjW7EALw_wcB">Link</a>',
                 '<a href= "https://www.sephora.com/product/bum-bum-mini-body-ritual-P507149?country_switch=us&lang=en&skuId=2713907&om_mmc=ppc-GG_17798154149___2713907__9011767_c&country_switch=us&lang=en&gad_source=1&gclid=Cj0KCQiApOyqBhDlARIsAGfnyMohlbmUwie5pTtm9beVwgjm2gkNlayk7MQxTSzU7zfVIDbYIxeEchwaAlt-EALw_wcB&gclsrc=aw.ds">Link</a>',
                 '<a href= "https://www.sephora.com/product/vanilla-perfume-discovery-set-P506469?country_switch=us&lang=en&skuId=2690378&om_mmc=ppc-GG_17791296865___2690378__9011767_c&country_switch=us&lang=en&gad_source=1&gclid=Cj0KCQiApOyqBhDlARIsAGfnyMrrmBSBsvu46s8S4apWDAbcBHBUUFwBdgoEwb3dY-wl5oWeL0J9LPwaAivwEALw_wcB&gclsrc=aw.ds">Link</a>',
                 '<a href= "https://www.sephora.com/product/cheirosa-travel-perfume-set-P507123">Link</a>',
                 '<a href= "https://www.amazon.com/Moisturizing-No-Sticky-Flavoured-Hydrating-Nourishing/dp/B0BY9QXTKD/ref=sr_1_4?crid=12K01GJRAMFPY&keywords=dior%2Blip%2Boil&qid=1700527277&sprefix=dior%2B%2Caps%2C201&sr=8-4&th=1">Link</a>',
                 '<a href= "https://www.ulta.com/p/soothing-barrier-support-serum-pimprod2041026?sku=2615437&cmpid=PS_Non!google!Product_Listing_Ads&utm_source=google&utm_medium=paidsearch&cagpspn=pla&CATCI=&CAAGID=&CAWELAID=330000200003123461&gad_source=1&gclid=Cj0KCQiApOyqBhDlARIsAGfnyMqyyLJia_0_DP8taTQcGkkvGcZzz6E1DEyGrRCq7ZFk45d8iw-ONO8aAhDnEALw_wcB">Link</a>',
                 '<a href= "https://www.amazon.com/EltaMD-Moisturizer-Hyaluronic-Mineral-Based-Protection/dp/B00J5KDCO2/ref=asc_df_B00J5KDCO2/?tag=hyprod-20&linkCode=df0&hvadid=312153186848&hvpos=&hvnetw=g&hvrand=8453952482864002813&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9011767&hvtargid=pla-435694681088&psc=1&mcid=c4873a6c4ec239a6bc003961e0692c4b&gclid=CjwKCAiAjfyqBhAsEiwA-UdzJCXcs3JIbeAKdLW4aQpZbYpI1gixicrfjPJXt8bef563xjKscXy3qhoCQJ0QAvD_BwE">Link</a>',
                 'Needs to be fixed',
                 '<a href= "https://beachwaver.com/products/beachwaver-b1-sunset?variant=32491644354639">Link</a>',
                 '<a href= "https://www.amazon.com/Jowmoy-Headband-Elastic-Makeup-Shower/dp/B0BR1HV8S3/ref=sr_1_13_sspa?crid=22T94JYPGMRAH&keywords=skincare%2Bheadbands&qid=1700786338&sprefix=skinecare%2Bheadbands%2Caps%2C91&sr=8-13-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9tdGY&th=1">Link</a>',
                 '<a href= "https://www.sephora.com/product/rare-beauty-by-selena-gomez-positive-light-liquid-luminizer-highlight-P38855877?country_switch=us&lang=en&skuId=2354157&om_mmc=ppc-GG_17789371101___2354157__9011767_c&country_switch=us&lang=en&gad_source=1&gclid=CjwKCAiAjfyqBhAsEiwA-UdzJPFGs1-Yt99u_q2qx8sb5zixFiU-pPaxHjuFTJSDQGeArv-wCkmTmBoC92QQAvD_BwE&gclsrc=aw.ds">Link</a>',
                 '<a href= "https://www.sephora.com/product/rare-beauty-by-selena-gomez-warm-wishes-effortless-bronzer-sticks-P479343?country_switch=us&lang=en&skuId=2640225&om_mmc=ppc-GG_17789371101___2518926__9011767_c&gad_source=1&gclid=CjwKCAiAjfyqBhAsEiwA-UdzJPVkjDGMW-TqioS8I3bo4Lh-Ej6rLWW0IaCrSD_yP10HjNZG5FEmFxoCj1AQAvD_BwE&gclsrc=aw.ds">Link</a>',
                 '<a href= "https://www.rarebeauty.com/products/soft-pinch-tinted-lip-oil?variant=40386673344647">Link</a>',
                 '<a href= "https://www.amazon.com/Squishmallows-Official-Kellytoy-Scarlett-Strawberry/dp/B09MBQYRC8/ref=sr_1_1?crid=3SLY7THCM401Y&keywords=squishmallows%2Bstrawberry&qid=1700786595&sprefix=squishmallowsstrawberry%2Caps%2C84&sr=8-1&th=1">Link</a>',
                 '<a href= "https://www.amazon.com/Squishmallows-Official-Kellytoy-Squishy-Stuffed/dp/B0BCDMK9VX/ref=asc_df_B0BCDMK9VX/?tag=hyprod-20&linkCode=df0&hvadid=634244744097&hvpos=&hvnetw=g&hvrand=7555567527683600637&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9011767&hvtargid=pla-1995099619157&psc=1&mcid=a3f93a12fc5a31d599f6f51d575d71e8">Link</a>',
                 '<a href= "https://www.amazon.com/SNUG-STAR-Portable-Keychain-Bracelet/dp/B09JK74SMC/ref=sr_1_47?crid=CF3N2IXA4XRA&keywords=keychain%2Bwallets&qid=1700509488&sprefix=keychain%2Bwallets%2Caps%2C98&sr=8-47&th=1">Link</a>',
                 '<a href= "https://www.amazon.com/Michael-Kors-Travel-Small-Holder/dp/B08CBL9J8X/ref=sr_1_16?crid=CF3N2IXA4XRA&keywords=keychain%2Bwallets&qid=1700509636&sprefix=keychain%2Bwallets%2Caps%2C98&sr=8-16&th=1">Link</a>',
                 'N/A',
                 '<a href= "https://www.ugg.com/women-slippers/tasman-slipper/5955.html">Link</a>',
                 '<a href= "https://www.amazon.com/CRZ-YOGA-Butterluxe-Waisted-Legging/dp/B09P1H6S8Y/ref=sr_1_1?crid=3Q6HIJG377F3S&keywords=crz%2Byoga%2Bleggings%2Bbutterluxe&qid=1700511116&sprefix=crz%2B%2Caps%2C98&sr=8-1&th=1&psc=1">Link</a>',
                 '<a href= "https://www.amazon.com/OQQ-Womens-Sleeve-Underscrubs-Stretch/dp/B0C9S94DNJ/ref=sr_1_4_sspa?crid=VCOK7F7I32H6&keywords=oqq+long+sleeve&qid=1700511028&sprefix=oqq+long+sleeve%2Caps%2C157&sr=8-4-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1">Link</a>',
                 '<a href= "https://www.amazon.com/PUMIEY-Bodysuit-Women-Racerback-Sleeveless/dp/B0BB72ZJWV/ref=sr_1_1_sspa?crid=F1XGUVXEJ07B&keywords=pumiey%2Bwomens%2Bhigh%2Bneck%2Bsleeveless%2Bbodysuit&qid=1700510703&sprefix=pumiey%2Bwomens%2Bhigh%2Caps%2C101&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1&psc=1">Link</a>',
                 '<a href= "https://www.amazon.com/PUMIEY-Bodysuit-Square-Sleeveless-Medium/dp/B0C3D6Z69D?ref_=ast_sto_dp&th=1&psc=1">Link</a>',
                 '<a href= "https://www.victoriassecret.com/us/vs/apparel-catalog/1122125700?genericId=11221257&choice=68H0&size1=M&size2=Regular&size1=M&cm_mmc=PLA-_-GOOGLE-_-VSD_VS_Lounge/Sport_PMAX-_-&gad_source=1&gclid=Cj0KCQiApOyqBhDlARIsAGfnyMrbMPcXHyqhdpLWx9dAmjM_7YjAh72QIZAnn77giFKUvIN4e97WvsEaAi9MEALw_wcB&gclsrc=aw.ds">Link</a>',
                 '<a href= "https://dandyworldwide.com/products/gift-giving-oversized-lux-hoodie-in-heather-gray?utm_source=google&utm_medium=cpc&utm_campaign=PerformanceMax2023&kw=&ad=&matchtype=&adposition=&c=&utm_term=&gad_source=1&gclid=Cj0KCQiApOyqBhDlARIsAGfnyMqrxjpJiLisPRp645KtgfX-8fmQogYKYvx_YSiID-K_htJ90xocGYUaAtefEALw_wcB">Link</a>',
                 '<a href= "https://us.brandymelville.com/products/skylar-lace-eyelet-tank?pr_prod_strat=use_description&pr_rec_id=efbe371c3&pr_rec_pid=6975790776529&pr_ref_pid=5833672491217&pr_seq=uniform">Link</a>',
                 '<a href= "https://whitefoxboutique.com/products/taking-off-top-baby-pink?variant=40719614804028">Link</a>',
                 '<a href= "https://www.aelfriceden.com/products/aelfric-eden-cartoon-line-character-print-hoodie?variant=42724483563682">Link</a>',
                 '<a href= "https://www.ae.com/us/en/p/aerie/bottoms/flare-bootcut-leggings/offline-by-aerie-real-me-high-waisted-crossover-flare-legging/0702_5230_788?menu=cat1090003">Link</a>',
                 'No longer available',
                 '<a href= "https://www.amazon.com/Vintage-Graphic-Hoodies-Sweatshirt-Pullover/dp/B0CNTT3DRH/ref=sr_1_3?crid=30JHSKYFTXAQS&keywords=sza%2Bhoodies&qid=1700797650&sprefix=sza%2Bhoodies%2Caps%2C85&sr=8-3&th=1">Link</a>',
                 'No longer available',
                 '<a href= "https://evryjewels.com/collections/best-sellers/products/lucky-necklace">Link</a>',
                 '<a href= "https://evryjewels.com/collections/best-sellers/products/charmed-earrings">Link</a>',
                 '<a href= "https://evryjewels.com/products/kendall-hoops?_pos=2&_sid=06913d34f&_ss=r&variant=40011664719949">Link</a>',
                 'Autotrader',
                    '<a href= "https://stockx.com/air-jordan-4-retro-frozen-moments-womens">Link</a>',
                    '<a href= "https://www.adidas.com/us/samba-classic/034563.html">Link</a>',
                    '<a href= "https://www.ugg.com/women-slippers/tasman-slipper/5955.html">Link</a>',
                    'N/A',
                    'N/A',
                    'N/A',
                    'N/A',
                    '<a href= "https://shop.lululemon.com/p/tops-long-sleeve/Swiftly-Tech-LS-2/_/prod9750543?color=4780">Link</a>',
                    '<a href= "https://store.melaniemartinezmusic.com/products/portals-moth-t-shirt">Link</a>',
                    'N/A',
                    '<a href= "https://www.amazon.com/Fastasticdeals-License-Grateful-Weatherproof-Accessories/dp/B0833F9M2W/ref=sxin_17_pa_sp_search_thematic_sspa?content-id=amzn1.sym.9e5188ef-9cc8-48bb-b834-24761033aedf%3Aamzn1.sym.9e5188ef-9cc8-48bb-b834-24761033aedf&crid=119WX907MS591&cv_ct_cx=grateful%2Bdead&keywords=grateful%2Bdead&pd_rd_i=B0833F9M2W&pd_rd_r=1fc6ec52-f695-4ba2-a4ee-d97ead51b05f&pd_rd_w=JZYRX&pd_rd_wg=FnEgf&pf_rd_p=9e5188ef-9cc8-48bb-b834-24761033aedf&pf_rd_r=2GPRWDMXRE46M2PHF45D&qid=1700166350&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&sprefix=grateful%2Bdead%2Caps%2C110&sr=1-1-364cf978-ce2a-480a-9bb0-bdb96faa0f61-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9zZWFyY2hfdGhlbWF0aWM&th=1">Link</a>',
                    '<a href= "https://www.amazon.com/Rhinowisdom-Airbrush-Kit-Cordless-Compressor/dp/B0C9JD5HR6/ref=sr_1_1_sspa?crid=2KNG8BYABEF42&keywords=nail+polish+airbrush&qid=1700170034&sprefix=nail+polish+air%2Caps%2C150&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1">Link</a>',
                    '<a href= "https://www.amazon.com/HXZQJECV-Dominic-Strawberry-Sweatshirts-XX-Large/dp/B0CF9HH3ZM/ref=sr_1_2?crid=26W4217ZIY6S3&keywords=dominic+fike+merch&qid=1700168834&sprefix=dominic+fike+%2Caps%2C110&sr=8-2">Link</a>',
                    '<a href= "https://www.amazon.com/Planet-Charms-Acrylic-Rhinestones-Jewelry/dp/B0C72K7LNN/ref=sr_1_97_sspa?crid=1Z9LG1LZYRSBN&keywords=nail%2Bgems&qid=1700170597&sprefix=nail%2Bgemsms%2Caps%2C166&sr=8-97-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGZfbmV4dA&th=1">Link</a>',
                    '<a href= "https://www.amazon.com/Assorted-Acrylic-Rhinestones-Manicure-Accessories/dp/B0BVFX6964/ref=sr_1_116?crid=1Z9LG1LZYRSBN&keywords=nail%2Bgems&qid=1700170662&sprefix=nail%2Bgemsms%2Caps%2C166&sr=8-116&th=1">Link</a>',
                    '<a href= "https://www.amazon.com/Rhinestones-Crystals-ss4-ss16-Flatback-Rhinestone/dp/B09WMDQY39/ref=sxbs_sbv_search_btf?content-id=amzn1.sym.563f7ac3-7aa9-48e0-841e-f45bb2322eae%3Aamzn1.sym.563f7ac3-7aa9-48e0-841e-f45bb2322eae&crid=1Z9LG1LZYRSBN&cv_ct_cx=nail%2Bgems&keywords=nail%2Bgems&pd_rd_i=B09WMDQY39&pd_rd_r=12b506fe-d284-4b08-9b81-37cd70325d3d&pd_rd_w=tujdG&pd_rd_wg=8UCg2&pf_rd_p=563f7ac3-7aa9-48e0-841e-f45bb2322eae&pf_rd_r=J58XTSY03EMDFC4WRX5K&qid=1700170753&sbo=RZvfv%2F%2FHxDF%2BO5021pAnSA%3D%3D&sprefix=nail%2Bgemsms%2Caps%2C166&sr=1-145-48f7baba-8e26-45f3-8811-e1a601ad20bf&th=1">Link</a>',
                    '<a href= "https://www.amazon.com/Pearls-Flatback-Pickup-Tweezer-Professional/dp/B0BJKT46B6/ref=sr_1_1_sspa?crid=1PPQPWDW5EP12&keywords=nail%2Bpearls&qid=1700170856&s=beauty&sprefix=nail%2Bpearls%2Cbeauty%2C121&sr=1-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1">Link</a>',
                    '<a href= "https://www.amazon.com/Sculpture-Non-Sticky-Extension-Silicone-Home-15g/dp/B0C4T7CY1Z/ref=sr_1_2_sspa?crid=3VLRVGRS0TXXG&keywords=nail%2Bsculpting%2Bgel&qid=1700170932&s=beauty&sprefix=nail%2Bsculp%2Cbeauty%2C122&sr=1-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1">Link</a>'
             ],
        ),
        ("Color", ['beige, brown, or black',
                  'black, coffee bean, dark grey, marzipan, estate blue, or quite grey',
                  'black, chocolate brown',
                  'black',
                  'black',
                  'Cream White',
                  'Mushroom',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'Gold',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'Black',
                  'N/A',
                  'N/A',
                  'N/A',
                  'Black',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'Grey',
                  'N/A',
                  'N/A',
                  'N/A',
                  'Silver',
                  'Black',
                  'Black and Dahlia Mauve',
                  'Espresso and Deep Luxe',
                  'Sienna',
                  'Light grey',
                  'Sanddrift',
                  'Baroque Brown/Sail and Coral Walk/Sail',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'good energy',
                  'serenity',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'chestnut',
                  'N/A',
                  'black and white',
                  'N/A',
                  'black or white',
                  'linen',
                  'N/A',
                  'N/A',
                  'Baby pink',
                  'N/A',
                  'forest green',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'N/A',
                  'white',
                   'N/A',
                   'Black',
                   'Chestnut',
                   'N/A',
                   'N/A',
                   'N/A',
                   'N/A',
                   'Black',
                   'Brown',
                   'N/A',
                   'N/A',
                   'N/A',
                   'navy',
                   'N/A',
                   'N/A',
                   'N/A',
                   'N/A',
                   'N/A'
                   ]),
        ("Price", ['33.99',
                  '28.99',
                  '39.99',
                  '32.99',
                  '24.88',
                  '33.99',
                  '243.00',
                  '18.99',
                  '15.95',
                  '9.20',
                  '17.99',
                  '9.40',
                  '0.00',
                  '15.00',
                  '36.10',
                  '0.00',
                  '6.99',
                  '14.50',
                  '0.00',
                  '0.00',
                  '7.99',
                  '13.00',
                  '21.98',
                  '39.00',
                  '19.20',
                  '31.99',
                  '19.99',
                  '29.95',
                  '139.99',
                  '98.47',
                  '74.99',
                  '109.99',
                  '29.60',
                  '36.10',
                  '38.99',
                  '21.99',
                  '100.00',
                  '36.00',
                  '31.47',
                  '18.99',
                  '249.99',
                  '74.99',
                  '40.85',
                  '160.00',
                  '19.20',
                  '0.00',
                  '0.00',
                  '48.00',
                  '78.00',
                  '40.00',
                  '78.00',
                  '60.00',
                  '75.00',
                  '0.00',
                  '0.00',
                  '20.00',
                  '34.00',
                  '49.00',
                  '13.00',
                  '14.50',
                  '17.00',
                  '25.00',
                  '15.95',
                  '42.00',
                  '30.00',
                  '34.00',
                  '6.99',
                  '17.00',
                  '36.10',
                  '0.00',
                  '69.00',
                  '6.98',
                  '25.00',
                  '26.00',
                  '20.00',
                  '41.99',
                  '25.99',
                  '12.95',
                  '32.00',
                  '0.00',
                  '110.00',
                  '32.00',
                  '28.99',
                  '25.99',
                  '25.99',
                  '54.95',
                  '89.00',
                  '18.00',
                  '34.99',
                  '59.95',
                  '32.97',
                  '0.00',
                  '39.99',
                  '0.00',
                  '15.00',
                  '9.20',
                  '9.40',
                  '0.00',
                  '340.00',
                  '90.00',
                  '110.00',
                  '0.00',
                  '0.00',
                  '0.00',
                  '0.00',
                  '78.00',
                  '35.00',
                  '0.00',
                  '17.99',
                  '39.99',
                  '18.99',
                  '8.98',
                  '6.99',
                  '9.99',
                  '6.42',
                  '8.99'
                   ]),
        ("Size", ['small',
                 'small',
                 'small',
                 'small',
                 'small',
                 'small',
                 '6.5 M',
                 '8',
                 '8',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'small',
                 '6',
                 'medium',
                 'small',
                 'small',
                 'small',
                 'N/A',
                 'N/A',
                 'Full',
                 '8.5',
                 'N/A',
                 'N/A',
                 'small',
                 'small',
                 '7',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 '4',
                 '4',
                 'small',
                 'small',
                 'XS',
                 'XS',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                 'women(8); men(7)',
                 'XS',
                 'S',
                 'XS',
                 'XS',
                 'small',
                 'large',
                 'regular fit',
                 'XS',
                 'large',
                 'medium long',
                 'small',
                 'large',
                 'large',
                 'N/A',
                 'N/A',
                 'N/A',
                 'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'small',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A',
                'N/A'
                  ]),
        (
            "Name",
            [
                'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Bird',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Lion',
                 'Horse',
                 'Horse',
                 'Horse',
                 'Horse',
                 'Horse',
                 'Horse',
                 'Horse',
                 'Horse',
                 'Horse',
                 'Horse',
                 'Horse',
                 'Horse',
                 'Horse',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Pandas',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish',
                 'Fish'
            ],
        ),
(
            "Status",
            [
                'Gigi purchase',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Gigi purchase',
                 'Pending',
                 'Pending',
                 'Gigi purchase',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Gigi purchase',
                 'Pending',
                 'Pending',
                 'Gigi purchase',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Gigi purchase',
                 'Pending',
                 'Pending',
                 'Gigi purchase',
                 'Pending',
                 'Gigi purchase',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Lion purchase',
                 'Lion purchase',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Gigi purchase',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Gigi purchase',
                 'Gigi purchase',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Austin purchase',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Gigi purchase',
                 'Gigi purchase',
                 'Gigi purchase',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending',
                 'Pending'
            ],
        ),
    ]
)

df = pd.DataFrame(data_election)

# plotly charts to be able to save as html files
import plotly.graph_objects as go
fig = go.Figure(data=[go.Table(
    header=dict(values=list(df.columns),
                fill_color='paleturquoise',
                align='left'),
    cells=dict(values=[df.Desc, df.Link, df.Color, df.Price, df.Size, df.Name, df.Status],
               fill_color='lavender',
               align='left'))
])

fig.show()

import plotly.io as pio
pio.write_html(fig, file='index.html', auto_open=True)


df['Price'] = df['Price'].astype(float).round(2)

df_grouped = df.groupby(['Name', 'Desc']).sum()[['Price']].reset_index()

# Sort the DataFrame by name and then by price in descending order
df_sorted = df_grouped.sort_values(by=['Name', 'Price'], ascending=[True, False])

# Use groupby to group by name and get the top 10 items for each group
top_10_items = df_sorted.groupby('Name').head(5)

bar_x = top_10_items['Name'].tolist()
bar_y = top_10_items['Price'].round(2).tolist()
bar_color = top_10_items['Desc']

purchased_only = df.loc[(df['Status'] != 'Pending'), :].reset_index()
purchased_only2 = purchased_only[['Name', 'Price']].groupby('Name').sum().reset_index()
pie_labels = purchased_only2['Name'].tolist()
pie_values = purchased_only2['Price'].tolist()
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = html.Div([
    dcc.Tabs([
        dcc.Tab([
            html.Div([
                dbc.Row(['2023 Xmas Tracking'], style={'font-weight': 'bold', 'font-size': '30px', 'padding': '20px'}, justify='center'),
                dbc.Row([
                    # first table
                    dbc.Col(html.Div(dash_table.DataTable(data=df.to_dict('records'),
                        columns=[{'id': c, 'name': c, 'presentation': 'markdown'} if c == 'Link' else {'id': c, 'name': c} for c in df.columns],
                        markdown_options={'html': True},
                        filter_action='native',
                        editable=True,
                        sort_action='native',
                        sort_mode='single',
                        page_current=0,
                        page_size=12,
                        style_cell={
                            'whiteSpace': 'normal',
                            'height': 'auto',
                            'maxWidth': '600px',  # for all cols
                            'minWidth': '100px',  # for all cols
                            'textAlign': 'left'
                        },
                        style_data={
                            'color': 'black',
                            'backgroundColor': 'white'
                        },
                        style_data_conditional=[
                            {
                                'if': {'row_index': 'odd'},
                                'backgroundColor': 'lightblue',  # set background color for odd rows
                            },

                            {
                                'if': {'row_index': 'even'},
                                'backgroundColor': 'white',  # set background color for even rows
                            }
                        ],
                        style_header={
                            'backgroundColor': '#000080',  # blue background color
                            'textAlign': 'center',  # center align column headers
                            'color': 'white',  # white font color
                            'fontWeight': 'bold'  # bold font
                        },
                        style_table={'width': '80%'}))),

                    dbc.Col(html.Div(dcc.Graph(
                        id='bar-graph',
                        figure=px.bar(x=bar_x,
                                      y=bar_y,
                                      color=bar_color,
                                      title='<b>Tracking By Name</b>',
                                      # color_discrete_sequence=[],
                                      labels={'x': 'Name', 'y': 'Price($)'},
                                      text_auto=True).update_traces(width=0.5, textfont_size=14).update_layout(autosize=False, width=900, height=700, paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)")
                    )))
                ]),
                dbc.Row([
                    dbc.Col(html.Div(dcc.Graph(
                        id='pie-graph',
                        figure=px.pie(names=pie_labels, title='<b>Purchased Totals</b>', values=pie_values).update_traces(textposition='inside', textinfo='value+label').update_layout(autosize=False, width=900, height=700, paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)")
                    )))
                ])
            ])
        ])
    ])
], className='dbc')


if __name__ == '__main__':
    app.run_server(debug=True, port=8052)

