name: Dash Plotly CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pandas
        pip install dash-bootstrap-components
        pip install openpyxl
        pip install -U kaleido


    - name: Run Dash App
      run: |
        python app.py

    - name: Debug
      run: |
        echo "Current Directory: $(pwd)"
        echo "Contents of 'docs' directory: $(ls -la docs)"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gauge-charts
        path: docs/*.png

    - name: Open image files
      run: xdg-open docs/*.png

