name: Run Python Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Use the latest version that supports node16

      - name: Set up Python
        uses: actions/setup-python@v4  # Use the latest version that supports node16
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install plotly
          pip install dash
          pip install dash_bootstrap_components

      - name: Run Python Script
        run: |
          python docs/xmas-trackingv2.py    
